blueprint:
  name: Aviso Telegram con detección de presencia - Horario
  description: Notificar en Telegram si se detecta presencia - Horario
  domain: automation
  source_url: https://github.com/jvaron-fidesol/hacs_fidesol/blob/main/telegram_fidesol_nave_laboral.yaml
  input:
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Home Assistant - Fidesol"'
      default: Home Assistant - Fidesol
    notification_message:
      name: Notification message (Required)
      description: 'Default: "Presencia Detectada!"'
      default: Presencia Detectada!
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    start_time:
      name: Start Time
      description: Time action should start
      default: "17:00:00"
      selector:
        time:
    end_time:
      name: End Time
      default: "00:00:00"
      description: Time action should stop
      selector:
        time:
trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
condition:
  alias: "Time"
  condition: time
  # At least one of the following is required.
  after: !input start_time
  before: !input end_time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
variables:
  notification_title: !input 'notification_title'
  notification_message: !input 'notification_message'
action:
- service: telegram_bot.send_message
  data:
    title: !input 'notification_title'
    message: !input 'notification_message'
    parse_mode: html
