blueprint:
  name: Aviso Telegram con detección de presencia - Hora
  description: Notificar en Telegram si se detecta presencia - Hora
  domain: automation
  source_url: https://github.com/jvaron-fidesol/hacs_fidesol/blob/main/telegram_fidesol_nave.yml
  input:
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Home Assistant - Fidesol"'
      default: Home Assistant - Fidesol
    notification_message:
      name: Notification message (Required)
      description: 'Default: "Presencia Detectada!"'
      default: Presencia Detectada!
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    start_time:
      name: Start time
      description: Select the start time of the notification period
      selector:
        time:
    end_time:
      name: End time
      description: Select the end time of the notification period
      selector:
        time:
  trigger:
    - platform: state
      entity_id: !input motion_entity
      from: "off"
      to: "on"
    - platform: time
      at: !input start_time
  condition:
    - condition: time
      after: !input start_time
      before: !input end_time
  variables:
    notification_title: !input 'notification_title'
    notification_message: !input 'notification_message'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.notify_telegram
    - wait_template: "{{ is_state('switch.notify_telegram', 'on') }}"
      timeout: '00:00:01'
    - condition: time
      after: !input start_time
      before: !input end_time
    - service: telegram_bot.send_message
      data:
        title: !input 'notification_title'
        message: !input 'notification_message'
        parse_mode: html
    - service: homeassistant.turn_off
      entity_id: switch.notify_telegram
